FROM pytorch/pytorch:2.7.1-cuda12.8-cudnn9-devel

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    jq \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY docker/stable_diffusion/requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir