# Metadata
job_name: random-forest-training

# Data
training_data_s3_path: "s3://bobby-demo/random-forest/data"
# validation_data_s3_path:
# test_data_s3_path:
model_output_s3_path: "s3://bobby-demo/random-forest/model-output"

# Code
source_code_dir: ./train/random_forest
source_code_entry_point_command: python random_forest.py --n_jobs 4 --max_depth 10 --n_estimators 120

# Compute
image_uri: "781297242028.dkr.ecr.us-west-2.amazonaws.com/sklearn:latest"
instance_type: ml.m5.2xlarge
instance_count: 1
instance_volume_size: 30
keep_alive_hours: 1
max_runtime_hours: 1

# Experiment tracking
mlflow_arn: "arn:aws:sagemaker:us-west-2:781297242028:mlflow-app/app-PWDIRFTCJKN5"
mlflow_experiment_name: random-forest-experiment

# Permissions
sagemaker_execution_role: "arn:aws:iam::781297242028:role/service-role/AmazonSageMaker-ExecutionRole-20200630T141851"