# Metadata
job_name: stable-diffusion-training

# Data
training_data_s3_path: "s3://bobby-demo/stable-diffusion/data"
model_output_s3_path: "s3://bobby-demo/stable-diffusion/model-output"

# Code
SOURCE_CODE_DIR: ./train/stable_diffusion
SOURCE_CODE_ENTRY_POINT_COMMAND: /bin/bash base.sh --config recipes/default-medium-g5_12x.yaml --training-script train_text_to_image_lora.py --accelerate-config accelerate_configs/ddp.yaml

# Compute
IMAGE_URI: "781297242028.dkr.ecr.us-west-2.amazonaws.com/stablediffusion:latest"
INSTANCE_TYPE: ml.g5.12xlarge
INSTANCE_COUNT: 1
INSTANCE_VOLUME_SIZE: 30
KEEP_ALIVE_HOURS: 1
MAX_RUNTIME_HOURS: 24

# Experiment tracking
MLFLOW_ARN: "arn:aws:sagemaker:us-west-2:781297242028:mlflow-app/app-PWDIRFTCJKN5"
MLFLOW_EXPERIMENT_NAME: random-forest-experiment

# Permissions
SAGEMAKER_EXECUTION_ROLE: "arn:aws:iam::781297242028:role/service-role/AmazonSageMaker-ExecutionRole-20200630T141851"