FROM python:3.13-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    jq \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY docker/sklearn/requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir